services:
  db:
    image: postgres:16-alpine
    container_name: stride-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stride
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stride"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    container_name: stride-api
    restart: always
    ports:
      - "3002:3002"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/web/node_modules
    environment:
      PORT: 3002
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/stride}
      JWT_SECRET: ${JWT_SECRET:-supersecretjwtkeyassessmentrival123!}
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: development
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3002/api/v1}
    container_name: stride-web
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/web/node_modules
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3002/api/v1}
      NODE_ENV: development
    depends_on:
      - api

volumes:
  pgdata:
